<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8954d9463c74c3eb2ce11b9c2c660f5d
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Cache\\' => 10,
        ),
        'D' => 
        array (
            'Dolondro\\GoogleAuthenticator\\' => 29,
        ),
        'B' => 
        array (
            'Base32\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Dolondro\\GoogleAuthenticator\\' => 
        array (
            0 => __DIR__ . '/..' . '/dolondro/google-authenticator/src',
        ),
        'Base32\\' => 
        array (
            0 => __DIR__ . '/..' . '/christian-riesen/base32/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8954d9463c74c3eb2ce11b9c2c660f5d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8954d9463c74c3eb2ce11b9c2c660f5d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8954d9463c74c3eb2ce11b9c2c660f5d::$classMap;

        }, null, ClassLoader::class);
    }
}
